spring:
  application:
    name: user-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/user_service
    username: postgres
    password: root

  flyway:
    url: jdbc:postgresql://localhost:5432/user_service
    baseline-on-migrate: true
    validate-on-migrate: false
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    enabled: true
  cloud:
    function:
      definition: userRegistrationDownstreamConsumer
    stream:
      bindings:
        userRegistrationDownstreamConsumer-in-0:
          destination: topic.user.registration
      kafka:
        binder:
          brokers: localhost:9092

server:
  port: 8082

# spring:
#   profiles:
#     active: test

# test_user_id: 4c0670ba-5556-4022-aead-00efe5d07290
test_user_id: 70c7ee0c-4dca-443f-a41f-c9c8caf10428

http:


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true