INSERT INTO users (id, username, display_name, avatar_url, email)
VALUES
    ('1', 'nguyen_van_anh1', 'Nguyễn Văn Anh', 'https://example.com/avatar1.jpg', 'nguyenvananh1@example.com'),
    ('2', 'tran_thi_binh2', 'Trần Thị Bình', 'https://example.com/avatar2.jpg', 'tranthibinh2@example.com'),
    ('3', 'le_hoang_dieu3', 'Lê Hoàng Diệu', 'https://example.com/avatar3.jpg', 'lehoangdieu3@example.com'),
    ('4', 'pham_quoc_tuan4', 'Phạm Quốc Tuấn', 'https://example.com/avatar4.jpg', 'phamquoctuan4@example.com'),
    ('5', 'vu_thi_huong5', 'Vũ Thị Hương', 'https://example.com/avatar5.jpg', 'vuthihuong5@example.com'),
    ('6', 'do_hong_son6', 'Đỗ Hồng Sơn', 'https://example.com/avatar6.jpg', 'dohongson6@example.com'),
    ('7', 'bui_thanh_hai7', 'Bùi Thanh Hải', 'https://example.com/avatar7.jpg', 'buithanhhai7@example.com'),
    ('8', 'nguyen_thi_lan8', 'Nguyễn Thị Lan', 'https://example.com/avatar8.jpg', 'nguyenthilan8@example.com'),
    ('9', 'hoang_anh_tuan9', 'Hoàng Anh Tuấn', 'https://example.com/avatar9.jpg', 'hoanganhtuan9@example.com'),
    ('10', 'pham_thu_hien10', 'Phạm Thu Hiền', 'https://example.com/avatar10.jpg', 'phamthuhien10@example.com'),
    ('11', 'tran_van_minh11', 'Trần Văn Minh', 'https://example.com/avatar11.jpg', 'tranvanminh11@example.com'),
    ('12', 'nguyen_thi_thu12', 'Nguyễn Thị Thu', 'https://example.com/avatar12.jpg', 'nguyenthithu12@example.com'),
    ('13', 'le_thanh_hoa13', 'Lê Thanh Hòa', 'https://example.com/avatar13.jpg', 'lethanhhoa13@example.com'),
    ('14', 'pham_van_long14', 'Phạm Văn Long', 'https://example.com/avatar14.jpg', 'phamvanlong14@example.com'),
    ('15', 'vu_hoang_mai15', 'Vũ Hoàng Mai', 'https://example.com/avatar15.jpg', 'vuhoangmai15@example.com'),
    ('16', 'do_thi_hong16', 'Đỗ Thị Hồng', 'https://example.com/avatar16.jpg', 'dothihong16@example.com'),
    ('17', 'bui_thi_bich17', 'Bùi Thị Bích', 'https://example.com/avatar17.jpg', 'buithibich17@example.com'),
    ('18', 'nguyen_quoc_toan18', 'Nguyễn Quốc Toàn', 'https://example.com/avatar18.jpg', 'nguyenquoctoan18@example.com'),
    ('19', 'hoang_thi_huyen19', 'Hoàng Thị Huyền', 'https://example.com/avatar19.jpg', 'hoangthihuyen19@example.com'),
    ('20', 'pham_thanh_tam20', 'Phạm Thanh Tâm', 'https://example.com/avatar20.jpg', 'phamthanhtam20@example.com'),
    ('21', 'tran_van_ha21', 'Trần Văn Hà', 'https://example.com/avatar21.jpg', 'tranvanha21@example.com'),
    ('22', 'nguyen_thi_mai22', 'Nguyễn Thị Mai', 'https://example.com/avatar22.jpg', 'nguyenthimai22@example.com'),
    ('23', 'le_van_thinh23', 'Lê Văn Thịnh', 'https://example.com/avatar23.jpg', 'levanthinh23@example.com'),
    ('24', 'pham_thi_lan24', 'Phạm Thị Lan', 'https://example.com/avatar24.jpg', 'phamthilan24@example.com'),
    ('25', 'vu_quang_nam25', 'Vũ Quang Nam', 'https://example.com/avatar25.jpg', 'vuquangnam25@example.com'),
    ('26', 'do_thi_hang26', 'Đỗ Thị Hằng', 'https://example.com/avatar26.jpg', 'dothihang26@example.com'),
    ('27', 'bui_van_kien27', 'Bùi Văn Kiên', 'https://example.com/avatar27.jpg', 'buivankien27@example.com'),
    ('28', 'nguyen_thi_quyen28', 'Nguyễn Thị Quyên', 'https://example.com/avatar28.jpg', 'nguyenthiquyen28@example.com'),
    ('29', 'hoang_quoc_huy29', 'Hoàng Quốc Huy', 'https://example.com/avatar29.jpg', 'hoangquochuy29@example.com'),
    ('30', 'pham_thi_thao30', 'Phạm Thị Thảo', 'https://example.com/avatar30.jpg', 'phamthithao30@example.com'),
    ('31', 'tran_van_tien31', 'Trần Văn Tiến', 'https://example.com/avatar31.jpg', 'tranvantien31@example.com'),
    ('32', 'nguyen_thi_le32', 'Nguyễn Thị Lệ', 'https://example.com/avatar32.jpg', 'nguyenthile32@example.com'),
    ('33', 'le_thi_hoa33', 'Lê Thị Hoa', 'https://example.com/avatar33.jpg', 'lethihoa33@example.com'),
    ('34', 'pham_van_hieu34', 'Phạm Văn Hiếu', 'https://example.com/avatar34.jpg', 'phamvanhieu34@example.com'),
    ('35', 'vu_thi_hoa35', 'Vũ Thị Hoa', 'https://example.com/avatar35.jpg', 'vuthihoa35@example.com'),
    ('36', 'do_van_khoa36', 'Đỗ Văn Khoa', 'https://example.com/avatar36.jpg', 'dovankhoa36@example.com'),
    ('37', 'bui_thi_trang37', 'Bùi Thị Trang', 'https://example.com/avatar37.jpg', 'buithitrang37@example.com'),
    ('38', 'nguyen_van_hieu38', 'Nguyễn Văn Hiếu', 'https://example.com/avatar38.jpg', 'nguyenvanhieu38@example.com'),
    ('39', 'hoang_thi_bich39', 'Hoàng Thị Bích', 'https://example.com/avatar39.jpg', 'hoangthibich39@example.com'),
    ('40', 'pham_van_phuc40', 'Phạm Văn Phúc', 'https://example.com/avatar40.jpg', 'phamvanphuc40@example.com'),
    ('41', 'tran_thi_hoa41', 'Trần Thị Hoa', 'https://example.com/avatar41.jpg', 'tranthihoa41@example.com'),
    ('42', 'nguyen_thi_hien42', 'Nguyễn Thị Hiền', 'https://example.com/avatar42.jpg', 'nguyenthihien42@example.com'),
    ('43', 'le_quoc_bao43', 'Lê Quốc Bảo', 'https://example.com/avatar43.jpg', 'lequocbao43@example.com'),
    ('44', 'pham_thi_tuyet44', 'Phạm Thị Tuyết', 'https://example.com/avatar44.jpg', 'phamthituyet44@example.com'),
    ('45', 'vu_quang_trung45', 'Vũ Quang Trung', 'https://example.com/avatar45.jpg', 'vuquangtrung45@example.com'),
    ('46', 'do_thi_bich46', 'Đỗ Thị Bích', 'https://example.com/avatar46.jpg', 'dothibich46@example.com'),
    ('47', 'bui_van_bao47', 'Bùi Văn Bảo', 'https://example.com/avatar47.jpg', 'buivanbao47@example.com'),
    ('48', 'nguyen_thi_dao48', 'Nguyễn Thị Đào', 'https://example.com/avatar48.jpg', 'nguyenthidao48@example.com'),
    ('49', 'hoang_quoc_toan49', 'Hoàng Quốc Toàn', 'https://example.com/avatar49.jpg', 'hoangquoctoan49@example.com'),
    ('50', 'pham_thi_huong50', 'Phạm Thị Hương', 'https://example.com/avatar50.jpg', 'phamthihuong50@example.com'),
    ('51', 'tran_van_dai51', 'Trần Văn Đại', 'https://example.com/avatar51.jpg', 'tranvandai51@example.com'),
    ('52', 'nguyen_thanh_hoa52', 'Nguyễn Thanh Hòa', 'https://example.com/avatar52.jpg', 'nguyenthanhhoa52@example.com'),
    ('53', 'le_van_dung53', 'Lê Văn Dũng', 'https://example.com/avatar53.jpg', 'levandung53@example.com'),
    ('54', 'pham_thi_ngoc54', 'Phạm Thị Ngọc', 'https://example.com/avatar54.jpg', 'phamthingoc54@example.com'),
    ('55', 'vu_thi_thu55', 'Vũ Thị Thu', 'https://example.com/avatar55.jpg', 'vuthithu55@example.com'),
    ('56', 'do_van_quan56', 'Đỗ Văn Quân', 'https://example.com/avatar56.jpg', 'dovanquan56@example.com'),
    ('57', 'bui_thi_ngoc57', 'Bùi Thị Ngọc', 'https://example.com/avatar57.jpg', 'buithingoc57@example.com'),
    ('58', 'nguyen_van_hoa58', 'Nguyễn Văn Hòa', 'https://example.com/avatar58.jpg', 'nguyenvanhoa58@example.com'),
    ('59', 'hoang_thi_linh59', 'Hoàng Thị Linh', 'https://example.com/avatar59.jpg', 'hoangthilinh59@example.com'),
    ('60', 'pham_van_khanh60', 'Phạm Văn Khánh', 'https://example.com/avatar60.jpg', 'phamvankhanh60@example.com'),
    ('61', 'tran_thi_thu61', 'Trần Thị Thu', 'https://example.com/avatar61.jpg', 'tranthithu61@example.com'),
    ('62', 'nguyen_van_tu62', 'Nguyễn Văn Tú', 'https://example.com/avatar62.jpg', 'nguyenvantu62@example.com'),
    ('63', 'le_van_thien63', 'Lê Văn Thiên', 'https://example.com/avatar63.jpg', 'levanthien63@example.com'),
    ('64', 'pham_thi_linh64', 'Phạm Thị Linh', 'https://example.com/avatar64.jpg', 'phamthilinh64@example.com'),
    ('65', 'vu_van_phuong65', 'Vũ Văn Phương', 'https://example.com/avatar65.jpg', 'vuvanphuong65@example.com'),
    ('66', 'do_thi_huong66', 'Đỗ Thị Hương', 'https://example.com/avatar66.jpg', 'dothihuong66@example.com'),
    ('67', 'bui_van_nam67', 'Bùi Văn Nam', 'https://example.com/avatar67.jpg', 'buivannam67@example.com'),
    ('68', 'nguyen_thi_tuyet68', 'Nguyễn Thị Tuyết', 'https://example.com/avatar68.jpg', 'nguyenthituyet68@example.com'),
    ('69', 'hoang_thi_thu69', 'Hoàng Thị Thu', 'https://example.com/avatar69.jpg', 'hoangthithu69@example.com'),
    ('70', 'pham_van_tai70', 'Phạm Văn Tài', 'https://example.com/avatar70.jpg', 'phamvantai70@example.com'),
    ('71', 'tran_van_quang71', 'Trần Văn Quang', 'https://example.com/avatar71.jpg', 'tranvanquang71@example.com'),
    ('72', 'nguyen_thi_hoa72', 'Nguyễn Thị Hoa', 'https://example.com/avatar72.jpg', 'nguyenthihoa72@example.com'),
    ('73', 'le_thi_hai73', 'Lê Thị Hải', 'https://example.com/avatar73.jpg', 'lethihai73@example.com'),
    ('74', 'pham_van_dung74', 'Phạm Văn Dũng', 'https://example.com/avatar74.jpg', 'phamvandung74@example.com'),
    ('75', 'vu_thi_thao75', 'Vũ Thị Thảo', 'https://example.com/avatar75.jpg', 'vuthithao75@example.com'),
    ('76', 'do_van_quyen76', 'Đỗ Văn Quyền', 'https://example.com/avatar76.jpg', 'dovanquyen76@example.com'),
    ('77', 'bui_thi_thanh77', 'Bùi Thị Thanh', 'https://example.com/avatar77.jpg', 'buithithanh77@example.com'),
    ('78', 'nguyen_van_duc78', 'Nguyễn Văn Đức', 'https://example.com/avatar78.jpg', 'nguyenvanduc78@example.com'),
    ('79', 'hoang_thi_phuong79', 'Hoàng Thị Phương', 'https://example.com/avatar79.jpg', 'hoangthiphuong79@example.com'),
    ('80', 'pham_thi_lan80', 'Phạm Thị Lan', 'https://example.com/avatar80.jpg', 'phamthilan80@example.com'),
    ('81', 'tran_van_dong81', 'Trần Văn Đông', 'https://example.com/avatar81.jpg', 'tranvandong81@example.com'),
    ('82', 'nguyen_quoc_binh82', 'Nguyễn Quốc Bình', 'https://example.com/avatar82.jpg', 'nguyenquocbinh82@example.com'),
    ('83', 'le_thanh_loan83', 'Lê Thanh Loan', 'https://example.com/avatar83.jpg', 'lethanhloan83@example.com'),
    ('84', 'pham_van_binh84', 'Phạm Văn Bình', 'https://example.com/avatar84.jpg', 'phamvanbinh84@example.com'),
    ('85', 'vu_thi_huyen85', 'Vũ Thị Huyền', 'https://example.com/avatar85.jpg', 'vuthihuyen85@example.com'),
    ('86', 'do_thi_hoai86', 'Đỗ Thị Hoài', 'https://example.com/avatar86.jpg', 'dothihoai86@example.com'),
    ('87', 'bui_van_hung87', 'Bùi Văn Hùng', 'https://example.com/avatar87.jpg', 'buivanhung87@example.com'),
    ('88', 'nguyen_thi_hong88', 'Nguyễn Thị Hồng', 'https://example.com/avatar88.jpg', 'nguyenthihong88@example.com'),
    ('89', 'hoang_van_huy89', 'Hoàng Văn Huy', 'https://example.com/avatar89.jpg', 'hoangvanhuy89@example.com'),
    ('90', 'pham_thi_hanh90', 'Phạm Thị Hạnh', 'https://example.com/avatar90.jpg', 'phamthihanh90@example.com'),
    ('91', 'tran_van_hung91', 'Trần Văn Hùng', 'https://example.com/avatar91.jpg', 'tranvanhung91@example.com'),
    ('92', 'nguyen_thi_bich92', 'Nguyễn Thị Bích', 'https://example.com/avatar92.jpg', 'nguyenthibich92@example.com'),
    ('93', 'le_van_hai93', 'Lê Văn Hải', 'https://example.com/avatar93.jpg', 'levanhai93@example.com'),
    ('94', 'pham_van_hoa94', 'Phạm Văn Hòa', 'https://example.com/avatar94.jpg', 'phamvanhoa94@example.com'),
    ('95', 'vu_thi_trang95', 'Vũ Thị Trang', 'https://example.com/avatar95.jpg', 'vuthitrang95@example.com'),
    ('96', 'do_thi_hoa96', 'Đỗ Thị Hoa', 'https://example.com/avatar96.jpg', 'dothihoa96@example.com'),
    ('97', 'bui_van_tuan97', 'Bùi Văn Tuấn', 'https://example.com/avatar97.jpg', 'buivantuan97@example.com'),
    ('98', 'nguyen_thi_tuyen98', 'Nguyễn Thị Tuyến', 'https://example.com/avatar98.jpg', 'nguyenthituyen98@example.com'),
    ('99', 'hoang_thi_ly99', 'Hoàng Thị Lý', 'https://example.com/avatar99.jpg', 'hoangthily99@example.com'),
    ('100', 'pham_thi_tuyen100', 'Phạm Thị Tuyến', 'https://example.com/avatar100.jpg', 'phamthituyen100@example.com');

-- Addresses for 100 users
INSERT INTO user_address (user_id, country, province, city, district, ward)
VALUES
    ('1', 'Vietnam', 'Hanoi', 'Hanoi', 'Cau Giay', 'Dich Vong'),
    ('2', 'Vietnam', 'Hanoi', 'Hanoi', 'Ba Dinh', 'Truc Bach'),
    ('3', 'Vietnam', 'Ho Chi Minh', 'Ho Chi Minh City', 'District 1', 'Ben Nghe'),
    ('4', 'Vietnam', 'Ho Chi Minh', 'Ho Chi Minh City', 'District 3', 'Ward 6'),
    ('5', 'Vietnam', 'Da Nang', 'Da Nang', 'Hai Chau', 'Hai Chau 1'),
    ('6', 'Vietnam', 'Hai Phong', 'Hai Phong', 'Le Chan', 'Du Hang'),
    ('7', 'Vietnam', 'Can Tho', 'Can Tho', 'Ninh Kieu', 'An Lac'),
    ('8', 'Vietnam', 'Thanh Hoa', 'Thanh Hoa', 'Thanh Hoa', 'Dong Ve'),
    ('9', 'Vietnam', 'Nghe An', 'Vinh', 'Nghe An', 'Cua Lo'),
    ('10', 'Vietnam', 'Hue', 'Hue', 'Hue', 'Phu Hoi'),
    ('11', 'Vietnam', 'Quang Nam', 'Hoi An', 'Quang Nam', 'Cam Ha'),
    ('12', 'Vietnam', 'Binh Dinh', 'Quy Nhon', 'Binh Dinh', 'Hoa Khanh'),
    ('13', 'Vietnam', 'Nha Trang', 'Khanh Hoa', 'Nha Trang', 'Phuoc Long'),
    ('14', 'Vietnam', 'Binh Duong', 'Thu Dau Mot', 'Binh Duong', 'Phu Tho'),
    ('15', 'Vietnam', 'Dong Nai', 'Bien Hoa', 'Dong Nai', 'Tam Hiep'),
    ('16', 'Vietnam', 'Vung Tau', 'Vung Tau', 'Ba Ria - Vung Tau', 'Thang Tam'),
    ('17', 'Vietnam', 'Long An', 'Tan An', 'Long An', 'Tan An'),
    ('18', 'Vietnam', 'Tien Giang', 'My Tho', 'Tien Giang', 'My Tho'),
    ('19', 'Vietnam', 'Can Tho', 'Can Tho', 'Ninh Kieu', 'An Lac'),
    ('20', 'Vietnam', 'Dak Lak', 'Buon Ma Thuot', 'Dak Lak', 'Thang Loi'),
    ('21', 'Vietnam', 'Da Lat', 'Da Lat', 'Lam Dong', 'Xuan An'),
    ('22', 'Vietnam', 'Phu Yen', 'Tuy Hoa', 'Phu Yen', 'Phuoc Hiep'),
    ('23', 'Vietnam', 'Quang Ngai', 'Quang Ngai', 'Quang Ngai', 'Tran Hung Dao'),
    ('24', 'Vietnam', 'Tra Vinh', 'Tra Vinh', 'Tra Vinh', '8'),
    ('25', 'Vietnam', 'An Giang', 'Long Xuyen', 'An Giang', 'My Thanh'),
    ('26', 'Vietnam', 'Kien Giang', 'Rach Gia', 'Kien Giang', 'Vin Kieu'),
    ('27', 'Vietnam', 'Ha Giang', 'Ha Giang', 'Ha Giang', 'Ngoc Duong'),
    ('28', 'Vietnam', 'Cao Bang', 'Cao Bang', 'Cao Bang', 'Hoa An'),
    ('29', 'Vietnam', 'Lang Son', 'Lang Son', 'Lang Son', 'Tam Thanh'),
    ('30', 'Vietnam', 'Yen Bai', 'Yen Bai', 'Yen Bai', 'Yen Ninh'),
    ('31', 'Vietnam', 'Lao Cai', 'Lao Cai', 'Lao Cai', 'Kim Tan'),
    ('32', 'Vietnam', 'Dien Bien', 'Dien Bien Phu', 'Dien Bien', 'Noong Het'),
    ('33', 'Vietnam', 'Son La', 'Son La', 'Son La', 'Chieng An'),
    ('34', 'Vietnam', 'Hoa Binh', 'Hoa Binh', 'Hoa Binh', 'Tan Lac'),
    ('35', 'Vietnam', 'Thai Nguyen', 'Thai Nguyen', 'Thai Nguyen', 'Quyet Thang'),
    ('36', 'Vietnam', 'Bac Kan', 'Bac Kan', 'Bac Kan', 'Hoang Quoc Viet'),
    ('37', 'Vietnam', 'Tuyen Quang', 'Tuyen Quang', 'Tuyen Quang', 'An Cu'),
    ('38', 'Vietnam', 'Lai Chau', 'Lai Chau', 'Lai Chau', 'Muong Te'),
    ('39', 'Vietnam', 'Dak Nong', 'Gia Nghia', 'Dak Nong', 'Quang Vinh'),
    ('40', 'Vietnam', 'Quang Binh', 'Dong Hoi', 'Quang Binh', 'Dong Hoi'),
    ('41', 'Vietnam', 'Bac Giang', 'Bac Giang', 'Bac Giang', 'Bac Giang'),
    ('42', 'Vietnam', 'Nam Dinh', 'Nam Dinh', 'Nam Dinh', 'Nam Dinh'),
    ('43', 'Vietnam', 'Thai Binh', 'Thai Binh', 'Thai Binh', 'Thai Binh'),
    ('44', 'Vietnam', 'Phu Tho', 'Phu Tho', 'Phu Tho', 'Phu Tho'),
    ('45', 'Vietnam', 'Bac Ninh', 'Bac Ninh', 'Bac Ninh', 'Bac Ninh'),
    ('46', 'Vietnam', 'Ha Nam', 'Phu Ly', 'Ha Nam', 'Phu Ly'),
    ('47', 'Vietnam', 'Hai Duong', 'Hai Duong', 'Hai Duong', 'Hai Duong'),
    ('48', 'Vietnam', 'Hung Yen', 'Hung Yen', 'Hung Yen', 'Hung Yen'),
    ('49', 'Vietnam', 'Ninh Binh', 'Ninh Binh', 'Ninh Binh', 'Ninh Binh'),
    ('50', 'Vietnam', 'Thanh Hoa', 'Thanh Hoa', 'Thanh Hoa', 'Thanh Hoa'),
    ('51', 'Vietnam', 'Ha Tinh', 'Ha Tinh', 'Ha Tinh', 'Ha Tinh'),
    ('52', 'Vietnam', 'Quang Tri', 'Dong Ha', 'Quang Tri', 'Dong Ha'),
    ('53', 'Vietnam', 'Quang Ninh', 'Ha Long', 'Quang Ninh', 'Ha Long'),
    ('54', 'Vietnam', 'Bac Lieu', 'Bac Lieu', 'Bac Lieu', 'Bac Lieu'),
    ('55', 'Vietnam', 'Ca Mau', 'Ca Mau', 'Ca Mau', 'Ca Mau'),
    ('56', 'Vietnam', 'Hau Giang', 'Vi Thanh', 'Hau Giang', 'Vi Thanh'),
    ('57', 'Vietnam', 'Kien Giang', 'Rach Gia', 'Kien Giang', 'Rach Gia'),
    ('58', 'Vietnam', 'Soc Trang', 'Soc Trang', 'Soc Trang', 'Soc Trang'),
    ('59', 'Vietnam', 'Bac Giang', 'Bac Giang', 'Bac Giang', 'Bac Giang'),
    ('60', 'Vietnam', 'Bac Lieu', 'Bac Lieu', 'Bac Lieu', 'Bac Lieu'),
    ('61', 'Vietnam', 'Bac Ninh', 'Bac Ninh', 'Bac Ninh', 'Bac Ninh'),
    ('62', 'Vietnam', 'Ben Tre', 'Ben Tre', 'Ben Tre', 'Ben Tre'),
    ('63', 'Vietnam', 'Binh Dinh', 'Binh Dinh', 'Binh Dinh', 'Binh Dinh'),
    ('64', 'Vietnam', 'Binh Duong', 'Binh Duong', 'Binh Duong', 'Binh Duong'),
    ('65', 'Vietnam', 'Binh Phuoc', 'Binh Phuoc', 'Binh Phuoc', 'Binh Phuoc'),
    ('66', 'Vietnam', 'Binh Thuan', 'Binh Thuan', 'Binh Thuan', 'Binh Thuan'),
    ('67', 'Vietnam', 'Ca Mau', 'Ca Mau', 'Ca Mau', 'Ca Mau'),
    ('68', 'Vietnam', 'Cao Bang', 'Cao Bang', 'Cao Bang', 'Cao Bang'),
    ('69', 'Vietnam', 'Da Nang', 'Da Nang', 'Da Nang', 'Da Nang'),
    ('70', 'Vietnam', 'Dac Lac', 'Dac Lac', 'Dac Lac', 'Dac Lac'),
    ('71', 'Vietnam', 'Dac Nong', 'Dac Nong', 'Dac Nong', 'Dac Nong'),
    ('72', 'Vietnam', 'Dong Nai', 'Dong Nai', 'Dong Nai', 'Dong Nai'),
    ('73', 'Vietnam', 'Dong Thap', 'Dong Thap', 'Dong Thap', 'Dong Thap'),
    ('74', 'Vietnam', 'Gia Lai', 'Gia Lai', 'Gia Lai', 'Gia Lai'),
    ('75', 'Vietnam', 'Ha Giang', 'Ha Giang', 'Ha Giang', 'Ha Giang'),
    ('76', 'Vietnam', 'Ha Nam', 'Ha Nam', 'Ha Nam', 'Ha Nam'),
    ('77', 'Vietnam', 'Ha Tinh', 'Ha Tinh', 'Ha Tinh', 'Ha Tinh'),
    ('78', 'Vietnam', 'Hai Duong', 'Hai Duong', 'Hai Duong', 'Hai Duong'),
    ('79', 'Vietnam', 'Hau Giang', 'Hau Giang', 'Hau Giang', 'Hau Giang'),
    ('80', 'Vietnam', 'Hoa Binh', 'Hoa Binh', 'Hoa Binh', 'Hoa Binh'),
    ('81', 'Vietnam', 'Hung Yen', 'Hung Yen', 'Hung Yen', 'Hung Yen'),
    ('82', 'Vietnam', 'Khanh Hoa', 'Khanh Hoa', 'Khanh Hoa', 'Khanh Hoa'),
    ('83', 'Vietnam', 'Kien Giang', 'Kien Giang', 'Kien Giang', 'Kien Giang'),
    ('84', 'Vietnam', 'Kon Tum', 'Kon Tum', 'Kon Tum', 'Kon Tum'),
    ('85', 'Vietnam', 'Lai Chau', 'Lai Chau', 'Lai Chau', 'Lai Chau'),
    ('86', 'Vietnam', 'Lam Dong', 'Lam Dong', 'Lam Dong', 'Lam Dong'),
    ('87', 'Vietnam', 'Lang Son', 'Lang Son', 'Lang Son', 'Lang Son'),
    ('88', 'Vietnam', 'Lao Cai', 'Lao Cai', 'Lao Cai', 'Lao Cai'),
    ('89', 'Vietnam', 'Long An', 'Long An', 'Long An', 'Long An'),
    ('90', 'Vietnam', 'Nam Dinh', 'Nam Dinh', 'Nam Dinh', 'Nam Dinh'),
    ('91', 'Vietnam', 'Nghe An', 'Nghe An', 'Nghe An', 'Nghe An'),
    ('92', 'Vietnam', 'Ninh Binh', 'Ninh Binh', 'Ninh Binh', 'Ninh Binh'),
    ('93', 'Vietnam', 'Ninh Thuan', 'Ninh Thuan', 'Ninh Thuan', 'Ninh Thuan'),
    ('94', 'Vietnam', 'Phu Tho', 'Phu Tho', 'Phu Tho', 'Phu Tho'),
    ('95', 'Vietnam', 'Phu Yen', 'Phu Yen', 'Phu Yen', 'Phu Yen'),
    ('96', 'Vietnam', 'Quang Binh', 'Quang Binh', 'Quang Binh', 'Quang Binh'),
    ('97', 'Vietnam', 'Quang Nam', 'Quang Nam', 'Quang Nam', 'Quang Nam'),
    ('98', 'Vietnam', 'Quang Ngai', 'Quang Ngai', 'Quang Ngai', 'Quang Ngai'),
    ('99', 'Vietnam', 'Quang Ninh', 'Quang Ninh', 'Quang Ninh', 'Quang Ninh'),
    ('100', 'Vietnam', 'Quang Tri', 'Quang Tri', 'Quang Tri', 'Quang Tri');
